version: "3"
services:
  node-quasar:
    build:
      context: ../node-quasar
      args:
        uid: ${CURRENT_UID}
    image: node-quasar:1.0.0
    container_name: mach.org.ua_node-quasar_dev
    user: ${CURRENT_UID}:${CURRENT_GID}
    volumes:
      - "../..:/code"
    working_dir: /code
    command: ./build.sh
    expose:
      - 8080
    ports:
      - "8080:8080"
    env_file:
      - ../.host.env
    environment:
      APP_ENV: local
      VIRTUAL_PORT: 8080

networks:
  default:
    external:
      name: nginx-proxy

