version: "3"
services:
  node-quasar:
    build: ../node-quasar
    image: node-quasar
    container_name: mach.org.ua_node-quasar
    volumes:
      - "../..:/code"
    working_dir: /code
    env_file:
      - ../node-quasar/.env
    tty: true
    stdin_open: true
  nginx:
    image: nginx:alpine
    container_name: mach.org.ua_nginx
    volumes:
      - "../../dist/spa-mat:/usr/share/nginx/html"
      - "../nginx/logs:/var/log/nginx"
      - "../nginx/conf.d:/etc/nginx/conf.d"
    expose:
      - 80
    env_file:
      - ../nginx/.env
networks:
  default:
    external:
      name: nginx-proxy

