version: "3"
services:
  node-quasar:
    build:
      context: ../node-quasar
      args:
        uid: ${CURRENT_UID}
    image: node-quasar:1.0.0
    container_name: mach.org.ua_node-quasar
    user: ${CURRENT_UID}:${CURRENT_GID}
    volumes:
      - "../..:/code"
    working_dir: /code
    environment:
      APP_ENV: production
    tty: true
    stdin_open: true
  nginx:
    image: nginx:alpine
    container_name: mach.org.ua_nginx
    volumes:
      - "../../dist/spa-mat:/usr/share/nginx/html"
      - "../nginx/logs:/var/log/nginx"
      - "../nginx/conf.d:/etc/nginx/conf.d"
    expose:
      - 80
    env_file:
      - ../.host.env
networks:
  default:
    external:
      name: nginx-proxy

